export const START_FILES_PROCESSING_TYPE = "START_FILES_PROCESSING_TYPE";
export const FINISH_FILES_PROCESSING_TYPE = "FINISH_FILES_PROCESSING_TYPE";
export const START_PRELOADER_TYPE = "START_PRELOADER_TYPE";
export const FINISH_PRELOADER_TYPE = "FINISH_PRELOADER_TYPE";
