export const SET_CHUNK_SIZE_TYPE = "SET_CHUNK_SIZE_TYPE";
export const START_FILES_PROCESSING_TYPE = "START_FILES_PROCESSING_TYPE";
export const FILE_IS_LOADED_TYPE = "FILE_IS_LOADED_TYPE";
export const FILE_IS_WRITTEN_TYPE = "FILE_IS_WRITTEN_TYPE";
export const FINISH_FILES_PROCESSING_TYPE = "FINISH_FILES_PROCESSING_TYPE";
export const FILES_PROCESSING_ERROR_TYPE = "FILES_PROCESSING_ERROR_TYPE";
export const START_PRELOADER_TYPE = "START_PRELOADER_TYPE";
export const FINISH_PRELOADER_TYPE = "FINISH_PRELOADER_TYPE";
